//
//  ClipboardReader.swift
//  Notch
//
//  SPDX-License-Identifier: GPL-3.0-only
//
//  Turns the current pasteboard into something worth keeping — or nothing.
//
//  Privacy rules, in order:
//   1. Anything marked with an nspasteboard.org marker (concealed,
//      transient, auto-generated) or a legacy equivalent is skipped. This is
//      how 1Password, Bitwarden, KeePassXC and friends flag copied secrets.
//   2. Copies made while a known password manager, or an app the user
//      excluded, is frontmost are skipped (checked by the manager, which
//      knows the frontmost app).
//
//  Kind precedence: files beat everything (Finder also puts the file name
//  and icon on the pasteboard), then whichever of text/image the source app
//  listed first — writers order types richest-first, so a browser's "Copy
//  Image" leads with TIFF while Word leads with RTF despite also including
//  a picture of the selection.
//

import AppKit
import ImageIO
import UniformTypeIdentifiers

/// Pasteboard contents read on the main thread. Images are still raw bytes:
/// decoding and thumbnailing happen off the main thread.
enum ClipboardCapture: Equatable {
    case text(String, rtf: Data?)
    case image(Data)
    case files([URL])
}

enum ClipboardReader {
    /// http://nspasteboard.org plus the legacy markers that predate it.
    static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("de.petermaurer.TransientPasteboardType"),
        .init("com.typeit4me.clipping"),
        .init("Pasteboard generator type"),
        .init("net.antelle.keeweb"),
    ]

    /// Password managers whose copies are dropped even if they forget to
    /// mark them concealed.
    static let passwordManagerBundleIDs: Set<String> = [
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
    ]

    /// Larger text is usually a log or a file's contents; storing it would
    /// bloat the history file and make every save slow.
    static let maxTextLength = 500_000
    static let maxImageBytes = 25 * 1024 * 1024
    static let maxRTFBytes = 2 * 1024 * 1024

    private static let imageTypes: [NSPasteboard.PasteboardType] = [.png, .tiff]
    private static let textTypes: Set<NSPasteboard.PasteboardType> = [
        .string, .rtf, .rtfd, .html,
        .init("public.utf8-plain-text"),
        .init("public.utf16-external-plain-text"),
    ]

    static func shouldIgnore(types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains(where: ignoredTypes.contains)
    }

    static func read(_ pasteboard: NSPasteboard) -> ClipboardCapture? {
        guard let types = pasteboard.types, !types.isEmpty, !shouldIgnore(types: types) else {
            return nil
        }

        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            return .files(urls)
        }

        let firstImage = types.firstIndex(where: imageTypes.contains)
        let firstText = types.firstIndex(where: textTypes.contains)
        let prefersImage = firstImage != nil && (firstText == nil || firstImage! < firstText!)

        if prefersImage, let image = readImage(pasteboard) {
            return image
        }
        if let text = readText(pasteboard) {
            return text
        }
        return readImage(pasteboard)
    }

    private static func readText(_ pasteboard: NSPasteboard) -> ClipboardCapture? {
        guard let string = pasteboard.string(forType: .string),
              !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              string.utf16.count <= maxTextLength
        else { return nil }

        let rtf = pasteboard.data(forType: .rtf).flatMap { $0.count <= maxRTFBytes ? $0 : nil }
        return .text(string, rtf: rtf)
    }

    private static func readImage(_ pasteboard: NSPasteboard) -> ClipboardCapture? {
        for type in imageTypes {
            if let data = pasteboard.data(forType: type), !data.isEmpty, data.count <= maxImageBytes {
                return .image(data)
            }
        }
        return nil
    }
}

/// A clipboard image re-encoded for storage: PNG (so every entry has one
/// format) plus a small thumbnail so the notch never decodes a full-size
/// screenshot just to draw a ~130-point card.
struct ProcessedClipboardImage: Sendable {
    let png: Data
    let thumbnailPNG: Data
    let pixelWidth: Int
    let pixelHeight: Int

    /// Cards crop the thumbnail to fill a square ~130pt card, so it's
    /// the *short* side that has to cover ~300px (2x) to stay sharp. The
    /// long side is capped so a panorama doesn't produce a huge thumbnail.
    static let thumbnailMinShortSide = 320
    static let thumbnailMaxLongSide = 1280

    /// Safe off the main thread: ImageIO only, no AppKit.
    static func process(_ data: Data) -> ProcessedClipboardImage? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let image = CGImageSourceCreateImageAtIndex(source, 0, nil)
        else { return nil }

        let isPNG = (CGImageSourceGetType(source) as String?) == UTType.png.identifier
        guard let png = isPNG ? data : encodePNG(image) else { return nil }

        let shortSide = max(min(image.width, image.height), 1)
        let longSide = max(image.width, image.height)
        let maxPixelSize = min(thumbnailMaxLongSide, thumbnailMinShortSide * longSide / shortSide)
        let thumbnailOptions: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxPixelSize,
        ]
        guard let thumbnail = CGImageSourceCreateThumbnailAtIndex(source, 0, thumbnailOptions as CFDictionary),
              let thumbnailPNG = encodePNG(thumbnail)
        else { return nil }

        return ProcessedClipboardImage(
            png: png,
            thumbnailPNG: thumbnailPNG,
            pixelWidth: image.width,
            pixelHeight: image.height
        )
    }

    private static func encodePNG(_ image: CGImage) -> Data? {
        let output = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(
            output, UTType.png.identifier as CFString, 1, nil
        ) else { return nil }
        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination) else { return nil }
        return output as Data
    }
}
